<?php
/**
 * Project card template part.
 *
 * Included with get_template_part() from the archive. Putting the card markup
 * in one file means a change to the card design happens once, not in every
 * template that shows a card. That is the reason template parts exist.
 *
 * Expects to be called inside The Loop.
 *
 * @package AgencyFlow
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

$agencyflow_meta  = agencyflow_get_project_meta( get_the_ID() );
$agencyflow_terms = get_the_terms( get_the_ID(), 'project_type' );

// Build the space-separated slug list that the JavaScript filter reads from
// the data-types attribute. This is the handover point between PHP and JS.
$agencyflow_slugs = array();
$agencyflow_names = array();

if ( ! is_wp_error( $agencyflow_terms ) && ! empty( $agencyflow_terms ) ) {
	foreach ( $agencyflow_terms as $agencyflow_term ) {
		$agencyflow_slugs[] = $agencyflow_term->slug;
		$agencyflow_names[] = $agencyflow_term->name;
	}
}
?>

<!--
	<article> is correct here: a project card is self-contained content that
	would still make sense if it were syndicated on its own. A <div> would
	carry no meaning at all.
-->
<article class="project-card" data-types="<?php echo esc_attr( implode( ' ', $agencyflow_slugs ) ); ?>">

	<?php if ( has_post_thumbnail() ) : ?>
		<div class="project-card__media">
			<a href="<?php the_permalink(); ?>" tabindex="-1" aria-hidden="true">
				<?php
				/*
				 * the_post_thumbnail() outputs a responsive <img> with srcset
				 * and sizes attributes generated by WordPress, so a phone
				 * downloads a small file and a desktop a large one. That is
				 * responsive images handled properly rather than by hand.
				 */
				the_post_thumbnail(
					'agencyflow-card',
					array(
						'loading' => 'lazy',
						'alt'     => esc_attr( get_the_title() ),
					)
				);
				?>
			</a>
		</div>
	<?php endif; ?>

	<div class="project-card__body">

		<?php if ( ! empty( $agencyflow_names ) ) : ?>
			<div class="tag-list">
				<?php foreach ( $agencyflow_names as $agencyflow_name ) : ?>
					<span class="tag"><?php echo esc_html( $agencyflow_name ); ?></span>
				<?php endforeach; ?>
			</div>
		<?php endif; ?>

		<!--
			h3 not h2: the archive page's h1 is the page title, each section
			heading is an h2, so a card title sits at level 3. Heading levels
			are a document outline, not font sizes.
		-->
		<h3 class="project-card__title">
			<a href="<?php the_permalink(); ?>"><?php the_title(); ?></a>
		</h3>

		<p class="project-card__excerpt">
			<?php echo esc_html( wp_strip_all_tags( get_the_excerpt() ) ); ?>
		</p>

		<div class="project-meta">
			<?php if ( ! empty( $agencyflow_meta['client'] ) ) : ?>
				<span class="project-meta__item">
					<span class="project-meta__key">Client</span>
					<span><?php echo esc_html( $agencyflow_meta['client'] ); ?></span>
				</span>
			<?php endif; ?>

			<?php if ( ! empty( $agencyflow_meta['completed'] ) ) : ?>
				<span class="project-meta__item">
					<span class="project-meta__key">Completed</span>
					<span><?php echo esc_html( $agencyflow_meta['completed'] ); ?></span>
				</span>
			<?php endif; ?>
		</div>

	</div>
</article>
